config/routes.rb
Rails.application.routes.draw do

  root 'boards#index'

  get   'signup' => 'users#new'
  get   'login'  => 'sessions#new'
  post  'login'  => 'sessions#create'
  get   'logout' => 'sessions#destroy'

  resources :users
  resources :boards do
    match 'color/:colored_number' => 'boards#color_number', via: :get, as: :color_number
    get   'reset' => 'boards#reset'
    get   'options/:row/:col' => 'boards#options', as: :show_options
    match 'add/:number' => 'boards#add', via: [:get,:post], as: :add_number
    match 'notes/:notes/' => 'boards#save_notes', via: [:get,:post], as: :save_notes
    match 'take_notes' => 'boards#take_notes', via: [:get,:post]
    match 'clear_notes' => 'boards#clear_notes', via: [:get,:post]
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:edit, :create, :new, :update]
end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :cells, dependent: :destroy

  accepts_nested_attributes_for :cells, allow_destroy: true

  def region_single(region) # 0-8
    return self.cells.where(region: region).map(&:value)
  end

  def region_double(row,col)
    return self.cells.where(row: row, column: col).map(&:value)
  end

  def sq_size
    return self.size * self.size
  end

  def copy_cells_to(id)
    board = Board.find(id)
    self.cells.each do |cell|
      ocell = board.cells.find_by(row: cell.row,column: cell.column)
      ocell.update_attributes!(value: cell.value,notes: cell.notes)
    end
  end

  def number_class(num,blue = false)
    klass = ''
    klass = 'blue'  if blue
    klass = 'red'   if self.number_bad?(num)
    klass = 'green' if self.number_finished?(num)
    return klass
  end

  def finished?
    sq_size = self.sq_size
    finished = true
    cells = self.cells
    sq_size.times do |i|
      break unless finished
      # finished &&= cells.where(value: i+1).size == sq_size # counts for 1-9 shows 9 times each
      finished &&= cells.find_by_sql("select `region`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{i+1} GROUP BY `region`").count{|c| c.c_val == 1} == sq_size
      finished &&= cells.find_by_sql("select `row`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{i+1} GROUP BY `row`").count{|c| c.c_val == 1} == sq_size
      finished &&= cells.find_by_sql("select `column`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{i+1} GROUP BY `column`").count{|c| c.c_val == 1} == sq_size
    end
    return finished
  end

  def number_finished?(number = 0)
    return false if number.to_i == 0
    cells = self.cells
    sq_size = self.sq_size
    return (
      cells.find_by_sql("select `region`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{number} GROUP BY `region`").count{|c| c.c_val == 1} == sq_size &&
      cells.find_by_sql("select `row`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{number} GROUP BY `row`").count{|c| c.c_val == 1} == sq_size &&
      cells.find_by_sql("select `column`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{number} GROUP BY `column`").count{|c| c.c_val == 1} == sq_size
    )
  end

  # returns hash of value => bools
  # ex: {1 => true,2 => false,3 => false,4 => false,5 => false,6 => false,7 => false,8 => false,9 => false}
  #     1 is finished others are not
  def numbers_finished
    sq_size = self.sq_size
    finished = (1..sq_size).map{|i| [i,true]}.to_h
    cells = self.cells
    finished.each_key do |i|
      finished[i] &&= cells.find_by_sql("select `region`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{i} GROUP BY `region`").count{|c| c.c_val == 1} == sq_size
      finished[i] &&= cells.find_by_sql("select `row`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{i} GROUP BY `row`").count{|c| c.c_val == 1} == sq_size
      finished[i] &&= cells.find_by_sql("select `column`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{i} GROUP BY `column`").count{|c| c.c_val == 1} == sq_size
    end
    return finished
  end

  def number_bad?(number=0)
    return false if number.to_i == 0
    cells = self.cells
    return !(
    cells.find_by_sql("select `region`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{number} GROUP BY `region`").count{|c| c.c_val>1} == 0 &&
      cells.find_by_sql("select `row`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{number} GROUP BY `row`").count{|c| c.c_val>1} == 0 &&
      cells.find_by_sql("select `column`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{number} GROUP BY `column`").count{|c| c.c_val>1} == 0
    )
  end

  def numbers_bad
    sq_size = self.sq_size
    good = (1..sq_size).map{|i| [i,true]}.to_h
    cells = self.cells
    good.each_key do |i|
      good[i] &&= cells.find_by_sql("select `region`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{i} GROUP BY `region`").count{|c| c.c_val>1} == 0
      good[i] &&= cells.find_by_sql("select `row`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{i} GROUP BY `row`").count{|c| c.c_val>1} == 0
      good[i] &&= cells.find_by_sql("select `column`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{i} GROUP BY `column`").count{|c| c.c_val>1} == 0
    end
    return good.each{|i,b| good[i] =!b}
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :logged_in_user
  before_action :get_board, only: [:show,:add,:options,:save_notes,:reset,:destroy,:take_notes,:clear_notes]

  def index
    @boards = current_user.boards
  end

  def destroy
    @board.destroy
    redirect_to boards_url
  end

  def show
    unless @board.user == current_user
      flash[:danger] = 'That is not your sudoku board! Creating a new board.'
      redirect_to new_board_url
    end
  end

  def options
    @row = params[:row]
    @col = params[:col]
    @cell = @board.cells.find_by(row: @row.to_i, column: @col.to_i)
    render(partial: 'boards/partials/options', layout: false)
  end

  def new
    @board = current_user.boards.create!(size: params[:size] || 3)
    init_board
    redirect_to board_url(@board)
  end

  def add
    cell = @board.cells.find_by(row: params[:row].to_i, column: params[:col].to_i)
    cell.update_attributes!(value: params[:number].to_i, notes: nil)
    # render(partial: 'boards/partials/show', layout: false)
    # fixme render show (non-partial) to fix #10 fully?
    rjr({html: (render_to_string(partial: 'boards/partials/show', layout: false)), number_finished: @board.number_finished?(cell.value)})
  end

  def save_notes
    cell = @board.cells.find_by(row: params[:row].to_i, column: params[:col].to_i)
    cell.update_attributes!(value: 0, notes: params[:notes].split(',').map(&:to_i))
    render(partial: 'boards/partials/show', layout: false)
  end

  def get_board
    @board = Board.find(params[:id] || params[:board_id])
  end

  def take_notes
    cells = @board.cells
    cells.each do |cell|
      notes = (1..9).to_a
      if cell.value.to_i == 0
        notes -= cells.where(row: cell.row).map(&:value)
        notes -= cells.where(column: cell.column).map(&:value)
        notes -= cells.where(region: cell.region).map(&:value)
        cell.notes = notes
      end
    end
    @board.save!
    render(partial: 'boards/partials/show', layout: false)
  end

  def clear_notes
    @board.cells.update_all(notes: nil)
    render(partial: 'boards/partials/show', layout: false)
  end

  def reset
    reset_board
    render(partial: 'boards/partials/show_empty', layout: false)
  end

  private

  def init_board
    size = @board.size
    sq = @board.sq_size
    cells = []
    sq.times do |r|
      sq.times do |c|
        cells << {row: r, column: c, region: size*(r/size)+(c/size), value: 0, notes: nil}
      end
    end
    @board.update_attributes!(cells_attributes: cells)
  end

  def reset_board
    cells = @board.cells.map{|c| c.attributes.except('created_at','updated_at').merge({value: 0, notes: nil})}
    @board.update_attributes!(cells_attributes: cells)
  end

  def board_params
    params.require(:board)
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/partials/_options.html.haml
.modal-content
  %table{id: 'mini-table'}
    %tbody
      - count = 1
      - 3.times do |i|
        %tr
          - 3. times do |j|
            %td.allow-hover{id: "cell#{count}", onclick: "manage_selection(this,#{count})", href: board_add_number_path(@board,'NUMBER')}
              = count
              - count = count + 1
.section.center
  = hidden_field_tag :row, @row
  = hidden_field_tag :col, @col
  = check_box_tag 'taking', 'notes', @cell.notes.size > 1, autocomplete: 'off', id: 'taking_notes'
  = label_tag 'taking_notes', 'Taking Notes', style: 'font-weight: normal;'
.modal-footer
  = link_to 'Cancel', '#', onclick: "closeModal('sudoku'); return false;", class: 'right btn-flat'
  = link_to 'Clear', board_add_number_path(@board,0), class: 'right btn-flat clear-cell'
  = link_to 'Save Notes', board_save_notes_path(@board,'NOTES'), class: 'right btn-flat save-notes', style: 'display: none', id:'saving_notes', onclick: 'save_notes(); return false;'
- if @cell.notes.size > 1
  - @cell.notes.each do |i|
    .notes{data: {notes: i}}
:javascript
  $("#taking_notes").change(function(){
    var save = $("#saving_notes");
    if (this.checked){
      save.css('display', 'inline');
      window.notes = [];
    }
    else {
      save.css('display', 'none')
    }
  }).trigger('change');
  $('.notes').each(function() {
    change_selection(Number($(this).data('notes')));
  });

app/views/boards/partials/_show.html.haml
- sq_size = @board.sq_size
- cells = @board.cells.to_a
- green = @board.numbers_finished
- red = @board.numbers_bad
- sq_size.times do |r|
  %tr
    - sq_size.times do |c|
      - cell = cells.find{|ce| ce.row == r && ce.column == c}
      - klass = ''
      - klass = 'green' if green[cell.value]
      - klass = 'red' if red[cell.value]
      - if @colored_number.to_i > 0
        - klass = 'blue' if cell.value == @colored_number
        - klass = 'blue lighten-2' if cell.notes.include?(@colored_number)
      %td.allow-hover.cell.list-numbers{href: board_show_options_path(@board,r,c), class: "#{klass} #{cell.notes.size > 0 ? 'notes-cell' : ''}", id: "row_#{r}_col_#{c}", data: {row: r, col: c, region: cell.region}}
        - if cell.value.to_i > 0
          = cell.value
        - elsif cell.notes.size > 0
          - notes = cell.notes
          - notes = notes+[nil]*(sq_size-notes.size) if notes.size < sq_size
          = "<div style='font-size: 8pt;width: auto'>".html_safe
          = "#{notes[0..2].join}#{'&nbsp;'*notes[0..2].count(nil)}<br>".html_safe
          = "#{notes[3..5].join}#{'&nbsp;'*notes[3..5].count(nil)}<br>".html_safe
          = "#{notes[6..8].join}#{'&nbsp;'*notes[6..8].count(nil)}</div>".html_safe
        - else
          = ('&nbsp;'*3).html_safe

app/views/boards/partials/_show_empty.html.haml
- size = @board.size
- sq_size = @board.sq_size
- sq_size.times do |r|
  %tr
    - sq_size.times do |c|
      %td.allow-hover.cell.list-numbers{id: "row_#{r}_col_#{c}"}
        = link_to board_show_options_path(@board,r,c), style: 'color: black;', data: {row: r, col: c, region: size*(r/size)+(c/size)} do
          = ('&nbsp;'*3).html_safe