config/routes.rb
Rails.application.routes.draw do

  root 'boards#index'

  get   'signup' => 'users#new'
  get   'login'  => 'sessions#new'
  post  'login'  => 'sessions#create'
  get   'logout' => 'sessions#destroy'

  resources :users
  resources :boards do
    match 'color/:colored_number' => 'boards#color_number', via: :get, as: :color_number
    get   'reset' => 'boards#reset'
    get   'options/:row/:col' => 'boards#options', as: :show_options
    match 'add/:number' => 'boards#add', via: [:get,:post], as: :add_number
    match 'notes/:notes/' => 'boards#save_notes', via: [:get,:post], as: :save_notes
    match 'take_notes' => 'boards#take_notes', via: [:get,:post]
    match 'clear_notes' => 'boards#clear_notes', via: [:get,:post]
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:edit, :create, :new, :update]
end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :cells, dependent: :destroy

  accepts_nested_attributes_for :cells, allow_destroy: true

  def region_single(region) # 0-8
    return self.cells.where(region: region).map(&:value)
  end

  def region_double(row,col)
    return self.cells.where(row: row, column: col).map(&:value)
  end

  def sq_size
    return self.size * self.size
  end

  def copy_cells_to(id)
    board = Board.find(id)
    self.cells.each do |cell|
      ocell = board.cells.find_by(row: cell.row,column: cell.column)
      ocell.update_attributes!(value: cell.value,notes: cell.notes)
    end
  end

  def number_class(num,blue = false)
    klass = ''
    klass = 'blue'  if blue
    klass = 'red'   if self.number_bad?(num)
    klass = 'green' if self.number_finished?(num)
    return klass
  end

  def finished?
    sq_size = self.sq_size
    finished = true
    cells = self.cells
    sq_size.times do |i|
      break unless finished
      # finished &&= cells.where(value: i+1).size == sq_size # counts for 1-9 shows 9 times each
      finished &&= cells.find_by_sql("select `region`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{i+1} GROUP BY `region`").count{|c| c.c_val == 1} == sq_size
      finished &&= cells.find_by_sql("select `row`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{i+1} GROUP BY `row`").count{|c| c.c_val == 1} == sq_size
      finished &&= cells.find_by_sql("select `column`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{i+1} GROUP BY `column`").count{|c| c.c_val == 1} == sq_size
    end
    return finished
  end

  def number_finished?(number = 0)
    return false if number.to_i == 0
    cells = self.cells
    sq_size = self.sq_size
    return (
      cells.find_by_sql("select `region`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{number} GROUP BY `region`").count{|c| c.c_val == 1} == sq_size &&
      cells.find_by_sql("select `row`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{number} GROUP BY `row`").count{|c| c.c_val == 1} == sq_size &&
      cells.find_by_sql("select `column`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{number} GROUP BY `column`").count{|c| c.c_val == 1} == sq_size
    )
  end

  # returns hash of value => bools
  # ex: {1 => true,2 => false,3 => false,4 => false,5 => false,6 => false,7 => false,8 => false,9 => false}
  #     1 is finished others are not
  def numbers_finished
    sq_size = self.sq_size
    finished = (1..sq_size).map{|i| [i,true]}.to_h
    cells = self.cells
    finished.each_key do |i|
      finished[i] &&= cells.find_by_sql("select `region`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{i} GROUP BY `region`").count{|c| c.c_val == 1} == sq_size
      finished[i] &&= cells.find_by_sql("select `row`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{i} GROUP BY `row`").count{|c| c.c_val == 1} == sq_size
      finished[i] &&= cells.find_by_sql("select `column`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{i} GROUP BY `column`").count{|c| c.c_val == 1} == sq_size
    end
    return finished
  end

  def number_bad?(number=0)
    return false if number.to_i == 0
    cells = self.cells
    return !(
    cells.find_by_sql("select `region`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{number} GROUP BY `region`").count{|c| c.c_val>1} == 0 &&
      cells.find_by_sql("select `row`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{number} GROUP BY `row`").count{|c| c.c_val>1} == 0 &&
      cells.find_by_sql("select `column`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{number} GROUP BY `column`").count{|c| c.c_val>1} == 0
    )
  end

  def numbers_bad
    sq_size = self.sq_size
    good = (1..sq_size).map{|i| [i,true]}.to_h
    cells = self.cells
    good.each_key do |i|
      good[i] &&= cells.find_by_sql("select `region`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{i} GROUP BY `region`").count{|c| c.c_val>1} == 0
      good[i] &&= cells.find_by_sql("select `row`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{i} GROUP BY `row`").count{|c| c.c_val>1} == 0
      good[i] &&= cells.find_by_sql("select `column`,count(value) as 'c_val' from cells where board_id=#{self.id} and value=#{i} GROUP BY `column`").count{|c| c.c_val>1} == 0
    end
    return good.each{|i,b| good[i] =!b}
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :logged_in_user
  before_action :get_board, only: [:show,:add,:options,:save_notes,:reset,:destroy,:take_notes,:clear_notes]

  def index
    @boards = current_user.boards
  end

  def destroy
    @board.destroy
    redirect_to boards_url
  end

  def show
    unless @board.user == current_user
      flash[:danger] = 'That is not your sudoku board! Creating a new board.'
      redirect_to new_board_url
    end
  end

  def options
    @row = params[:row]
    @col = params[:col]
    @cell = @board.cells.find_by(row: @row.to_i, column: @col.to_i)
    render(partial: 'boards/partials/options', layout: false)
  end

  def new
    @board = current_user.boards.create!(size: params[:size] || 3)
    init_board
    redirect_to board_url(@board)
  end

  def add
    cell = @board.cells.find_by(row: params[:row].to_i, column: params[:col].to_i)
    cell.update_attributes!(value: params[:number].to_i, notes: nil)
    # render(partial: 'boards/partials/show', layout: false)
    # fixme render show (non-partial) to fix #10 fully?
    rjr({html: (render_to_string(partial: 'boards/partials/show', layout: false)), number_finished: @board.number_finished?(cell.value)})
  end

  def save_notes
    cell = @board.cells.find_by(row: params[:row].to_i, column: params[:col].to_i)
    cell.update_attributes!(value: 0, notes: params[:notes].split(',').map(&:to_i))
    render(partial: 'boards/partials/show', layout: false)
  end

  def get_board
    @board = Board.find(params[:id] || params[:board_id])
  end

  def take_notes
    cells = @board.cells
    cells.each do |cell|
      notes = (1..9).to_a
      if cell.value.to_i == 0
        notes -= cells.where(row: cell.row).map(&:value)
        notes -= cells.where(column: cell.column).map(&:value)
        notes -= cells.where(region: cell.region).map(&:value)
        cell.notes = notes
      end
    end
    @board.save!
    render(partial: 'boards/partials/show', layout: false)
  end

  def clear_notes
    @board.cells.update_all(notes: nil)
    render(partial: 'boards/partials/show', layout: false)
  end

  def reset
    reset_board
    render(partial: 'boards/partials/show_empty', layout: false)
  end

  private

  def init_board
    size = @board.size
    sq = @board.sq_size
    cells = []
    sq.times do |r|
      sq.times do |c|
        cells << {row: r, column: c, region: size*(r/size)+(c/size), value: 0, notes: nil}
      end
    end
    @board.update_attributes!(cells_attributes: cells)
  end

  def reset_board
    cells = @board.cells.map{|c| c.attributes.except('created_at','updated_at').merge({value: 0, notes: nil})}
    @board.update_attributes!(cells_attributes: cells)
  end

  def board_params
    params.require(:board)
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/index.html.haml
- if @boards.size == 0
  You don't have any sudoku boards
- else
  .section
  - @boards.each do |board|
    .row
      .col.s2
        = link_to 'Edit', board_path(board), class: 'btn btn-flat'
      .col.s8
        - if board.cells.where(value: 0).size == 81  || (board.cells.where(value: 1).size == 0 && board.cells.where(value: 2).size == 0 && board.cells.where(value: 3).size == 0 && board.cells.where(value: 4).size == 0 && board.cells.where(value: 5).size == 0 && board.cells.where(value: 6).size == 0 && board.cells.where(value: 7).size == 0 && board.cells.where(value: 8).size == 0 && board.cells.where(value: 9).size == 0)
          %span{style: 'text-align: center;'}
            This board is empty
        - elsif board.finished?
          %span{style: 'text-align: center;'}
            This board is finished
        - else
          %table.bordered
            %tbody.sudoku-board
              - board.sq_size.times do |r|
                %tr
                  - board.cells.where(row: r).order(:column).each do |cell|
                    %td{style: ':hover{ background: }'}
                      = "#{cell.value == 0 || cell.notes.length > 0 ? '&nbsp;' : cell.value}".html_safe
      .col.s2
        = link_to 'delete', board_path(board), class: 'btn btn-flat', method: :delete, data: { confirm: 'You sure?' }
    %hr
.fixed-action-btn{ style: 'bottom:45px; right:24px;' }
  = link_to '<i class="material-icons">add</i>'.html_safe, new_board_path, class: 'btn-floating btn-large'
  %span.fab-tip New sudoku

app/views/boards/show.html.haml
- provide(:title, 'Sudoku')
.container
  %h3 Sudoku Board
  .row
    .col= link_to 'Your Sudoku boards', boards_path, class: 'btn-flat waves-effect'
    .col= link_to 'Reset Board', board_reset_path(@board), class: 'btn-flat waves-effect reset-board'
  .row
    .col= link_to '1', '#', style: 'color: black;', class: "btn-floating waves-effect waves-circle #{@board.number_finished?(1) ? 'green' : ''} red highlight-number"
    .col= link_to '2', '#', style: 'color: black;', class: "btn-floating waves-effect waves-circle #{@board.number_finished?(2) ? 'green' : ''} red highlight-number"
    .col= link_to '3', '#', style: 'color: black;', class: "btn-floating waves-effect waves-circle #{@board.number_finished?(3) ? 'green' : ''} red highlight-number"
    .col= link_to '4', '#', style: 'color: black;', class: "btn-floating waves-effect waves-circle #{@board.number_finished?(4) ? 'green' : ''} red highlight-number"
    .col= link_to '5', '#', style: 'color: black;', class: "btn-floating waves-effect waves-circle #{@board.number_finished?(5) ? 'green' : ''} red highlight-number"
    .col= link_to '6', '#', style: 'color: black;', class: "btn-floating waves-effect waves-circle #{@board.number_finished?(6) ? 'green' : ''} red highlight-number"
    .col= link_to '7', '#', style: 'color: black;', class: "btn-floating waves-effect waves-circle #{@board.number_finished?(7) ? 'green' : ''} red highlight-number"
    .col= link_to '8', '#', style: 'color: black;', class: "btn-floating waves-effect waves-circle #{@board.number_finished?(8) ? 'green' : ''} red highlight-number"
    .col= link_to '9', '#', style: 'color: black;', class: "btn-floating waves-effect waves-circle #{@board.number_finished?(9) ? 'green' : ''} red highlight-number"
    .col.s2= link_to 'Fill Notes', board_take_notes_path(@board), class: 'btn-flat take-notes'
    .col.s2= link_to 'Clear Notes', board_clear_notes_path(@board), class: 'btn-flat clear-notes'
  .row
    .col.s12
      %table.centered.bordered#full-table
        %tbody.sudoku-board
          = render 'boards/partials/show'
  .section
#sudoku_modal.modal